import { People } from "types/project-types";

const peopleDataComplex: People[] = [{
    peopleId: 12345,
    firstName: "Nichole",
    lastName: "Rich",
    email: "nichole.rich@gmail.com",
    phone: "555.555.5555",
    imageUrl: "string",
    activeFile: true,
    martialStatus: "Married",
    ssn: "555-55-5555",
    dob: "02-02-1989",
    role: ["Admin","Staff","Clien"],
    address1: "Address1 From Address",
    address2: "Address2 From Address",
    city: "Detroit",
    state: "Michigan",
    zipCode: "48091",
  },
  {
    peopleId: 12345,
    firstName: "Angie",
    lastName: "Rich",
    email: "Angie.rich@gmail.com", 
    phone: "555.555.5555",
    imageUrl: "string",
    activeFile: true,
    martialStatus: "Married",
    ssn: "555-55-5555",
    dob: "02-02-1989",
    role: ["Admin","Staff","Clien"],
    address1: "Address1 From Address",
    address2: "Address2 From Address",
    city: "Detroit",
    state: "Michigan",
    zipCode: "48091",
  },{
    peopleId: 12345,
    firstName: "Angie",
    lastName: "Rich",
    email: "Angie.rich@gmail.com", 
    phone: "555.555.5555",
    imageUrl: "string",
    activeFile: true,
    martialStatus: "Married",
    ssn: "555-55-5555",
    dob: "02-02-1989",
    role: ["Admin","Staff","Clien"],
    address1: "Address1 From Address",
    address2: "Address2 From Address",
    city: "Detroit",
    state: "Michigan",
    zipCode: "48091",
  },{
    peopleId: 12345,
    firstName: "Angie",
    lastName: "Rich",
    email: "Angie.rich@gmail.com", 
    phone: "555.555.5555",
    imageUrl: "string",
    activeFile: true,
    martialStatus: "Married",
    ssn: "555-55-5555",
    dob: "02-02-1989",
    role: ["Admin","Staff","Clien"],
    address1: "Address1 From Address",
    address2: "Address2 From Address",
    city: "Detroit",
    state: "Michigan",
    zipCode: "48091",
  },{
    peopleId: 12345,
    firstName: "Angie",
    lastName: "Rich",
    email: "Angie.rich@gmail.com", 
    phone: "555.555.5555",
    imageUrl: "string",
    activeFile: true,
    martialStatus: "Married",
    ssn: "555-55-5555",
    dob: "02-02-1989",
    role: ["Admin","Staff","Clien"],
    address1: "Address1 From Address",
    address2: "Address2 From Address",
    city: "Detroit",
    state: "Michigan",
    zipCode: "48091",
  },{
    peopleId: 12345,
    firstName: "Angie",
    lastName: "Rich",
    email: "Angie.rich@gmail.com", 
    phone: "555.555.5555",
    imageUrl: "string",
    activeFile: true,
    martialStatus: "Married",
    ssn: "555-55-5555",
    dob: "02-02-1989",
    role: ["Admin","Staff","Clien"],
    address1: "Address1 From Address",
    address2: "Address2 From Address",
    city: "Detroit",
    state: "Michigan",
    zipCode: "48091",
  },{
    peopleId: 12345,
    firstName: "Angie",
    lastName: "Rich",
    email: "Angie.rich@gmail.com", 
    phone: "555.555.5555",
    imageUrl: "string",
    activeFile: true,
    martialStatus: "Married",
    ssn: "555-55-5555",
    dob: "02-02-1989",
    role: ["Admin","Staff","Clien"],
    address1: "Address1 From Address",
    address2: "Address2 From Address",
    city: "Detroit",
    state: "Michigan",
    zipCode: "48091",
  },{
    peopleId: 12345,
    firstName: "Angie",
    lastName: "Rich",
    email: "Angie.rich@gmail.com", 
    phone: "555.555.5555",
    imageUrl: "string",
    activeFile: true,
    martialStatus: "Married",
    ssn: "555-55-5555",
    dob: "02-02-1989",
    role: ["Admin","Staff","Clien"],
    address1: "Address1 From Address",
    address2: "Address2 From Address",
    city: "Detroit",
    state: "Michigan",
    zipCode: "48091",
  },
]
export default peopleDataComplex;